using Avalonia.Input;

namespace StorageHub.Desktop.Configuration;

/// <summary>
/// Converts a <see cref="KeyGesture"/> to and from the canonical text stored in
/// <c>config.shortcuts.json</c>, for example <c>Ctrl+Shift+S</c>.
/// </summary>
/// <remarks>
/// <para>
/// A chord is deliberately not persisted as its enum. CodeLogic installs a
/// <c>JsonStringEnumConverter</c> with a camel-case policy, and the WinForms <c>Keys</c> this used
/// to hold is a <c>[Flags]</c> enum carrying dozens of aliases -- <c>Ctrl+Shift+S</c> would be
/// written as <c>"control, shiftKey, s"</c>, which is neither readable nor reliably round-trippable.
/// </para>
/// <para>
/// The modifier order is fixed at Ctrl, Alt, Shift so that the same binding always produces the
/// same bytes, and a diff of the file shows only what a user actually changed.
/// </para>
/// <para>
/// <b>The stored spelling is WinForms', not Avalonia's.</b> Twenty-one keys are spelled differently
/// by the two enums, and not only the ones you would guess: PageDown was stored as <c>Next</c>,
/// CapsLock as <c>Capital</c>, OemQuestion as <c>Oem2</c>, Return as <c>Enter</c>. Emitting
/// Avalonia's spelling would silently rewrite an existing <c>config.shortcuts.json</c> and, worse,
/// an older build reading it back would drop those bindings as unrecognised. Both spellings parse;
/// only the original is written.
/// </para>
/// <para>
/// Deliberately not <c>KeyGesture.Parse</c>/<c>ToString</c>, which use their own syntax and would
/// change the file for every binding at once.
/// </para>
/// </remarks>
internal static class ShortcutChord
{
    private const string None = "Unassigned";

    /// <summary>The longest text this will parse, so a hostile file cannot make it work hard.</summary>
    private const int MaximumLength = 64;

    /// <summary>
    /// The keys whose stored name differs from the Avalonia member name.
    /// </summary>
    /// <remarks>
    /// Generated by comparing the two enums rather than written by hand, because the differences are
    /// not the obvious ones: PageDown was stored as "Next", CapsLock as "Capital", OemQuestion as
    /// "Oem2". Twenty-one keys differ in all. A hand-written guess would have covered two of them
    /// and quietly broken the rest.
    /// </remarks>
    private static readonly Dictionary<Key, string> StoredNames = new()
    {
        [Key.CapsLock] = "Capital",
        [Key.CrSel] = "Crsel",
        [Key.ExSel] = "Exsel",
        [Key.HangulMode] = "KanaMode",
        [Key.HanjaMode] = "KanjiMode",
        [Key.ImeAccept] = "IMEAceept",
        [Key.ImeConvert] = "IMEConvert",
        [Key.ImeModeChange] = "IMEModeChange",
        [Key.ImeNonConvert] = "IMENonconvert",
        [Key.Oem3] = "Oemtilde",
        [Key.OemBackslash] = "Oem102",
        [Key.OemCloseBrackets] = "Oem6",
        [Key.OemComma] = "Oemcomma",
        [Key.OemPlus] = "Oemplus",
        [Key.OemQuestion] = "Oem2",
        [Key.PageDown] = "Next",
        [Key.Return] = "Enter",

        // Four more where Avalonia shares the value with a DBE member declared first, so the key
        // parses from the stored name but reports a different one back. Only a round-trip test
        // finds these; comparing the two enums' names does not.
        [Key.DbeNoRoman] = "Attn",
        [Key.DbeFlushString] = "EraseEof",
        [Key.DbeCodeInput] = "Play",
        [Key.DbeEnterDialogConversionMode] = "Pa1",
    };

    internal static string Format(KeyGesture? gesture)
    {
        if (gesture is null) return None;

        var chord = new List<string>(4);
        if (gesture.KeyModifiers.HasFlag(KeyModifiers.Control)) chord.Add("Ctrl");
        if (gesture.KeyModifiers.HasFlag(KeyModifiers.Alt)) chord.Add("Alt");
        if (gesture.KeyModifiers.HasFlag(KeyModifiers.Shift)) chord.Add("Shift");
        chord.Add(StoredName(gesture.Key));
        return string.Join('+', chord);
    }

    /// <summary>
    /// Reads a chord back, or returns null when the text is not one. Null rather than an exception
    /// because the caller is always reading a file a user may have edited, and one bad line should
    /// cost that one binding rather than the whole file.
    /// </summary>
    /// <remarks>
    /// An unassigned chord and an unreadable one are both null here, which the caller distinguishes
    /// by whether the text was <c>Unassigned</c>. That is why <see cref="TryParse"/> returns a bool.
    /// </remarks>
    internal static bool TryParse(string? value, out KeyGesture? gesture)
    {
        gesture = null;
        if (string.IsNullOrWhiteSpace(value) || value.Length > MaximumLength) return false;

        var text = value.Trim();
        if (string.Equals(text, None, StringComparison.OrdinalIgnoreCase)) return true;

        var parts = text.Split('+', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length is 0 or > 4) return false;

        var modifiers = KeyModifiers.None;
        for (var index = 0; index < parts.Length - 1; index++)
        {
            var modifier = parts[index] switch
            {
                "Ctrl" or "Control" => KeyModifiers.Control,
                "Alt" => KeyModifiers.Alt,
                "Shift" => KeyModifiers.Shift,
                _ => KeyModifiers.None,
            };

            // An unrecognised or repeated modifier means the text was not written by Format, and
            // guessing at what was meant is how a user ends up with a binding they did not choose.
            if (modifier == KeyModifiers.None || modifiers.HasFlag(modifier)) return false;
            modifiers |= modifier;
        }

        if (!TryParseKey(parts[^1], out var key)) return false;

        gesture = new KeyGesture(key, modifiers);
        return true;
    }

    /// <summary>
    /// The name a key is written under, which is the WinForms spelling where the two differ.
    /// </summary>
    /// <remarks>
    /// Exposed because the WinForms shell's Keys adapter needs exactly the same knowledge, in the
    /// other direction. One table with two users beats two tables that agree until they do not.
    /// </remarks>
    internal static string StoredName(Key key) =>
        StoredNames.TryGetValue(key, out var stored) ? stored : key.ToString();

    /// <summary>Accepts the stored spelling and Avalonia's, and nothing else.</summary>
    internal static bool TryParseKey(string name, out Key key)
    {
        foreach (var (candidate, stored) in StoredNames)
        {
            if (string.Equals(name, stored, StringComparison.Ordinal))
            {
                key = candidate;
                return true;
            }
        }

        return Enum.TryParse(name, ignoreCase: false, out key) && Enum.IsDefined(key);
    }

    /// <summary>
    /// The stored form of a whole override table, dropping any binding the current build no longer
    /// recognises rather than carrying it forward invisibly.
    /// </summary>
    internal static Dictionary<string, string> Format(IReadOnlyDictionary<string, KeyGesture?> shortcuts)
    {
        ArgumentNullException.ThrowIfNull(shortcuts);
        return shortcuts.ToDictionary(
            entry => entry.Key,
            entry => Format(entry.Value),
            StringComparer.Ordinal);
    }

    internal static Dictionary<string, KeyGesture?> Parse(IReadOnlyDictionary<string, string>? shortcuts)
    {
        var result = new Dictionary<string, KeyGesture?>(StringComparer.Ordinal);
        if (shortcuts is null) return result;

        foreach (var entry in shortcuts)
        {
            if (!string.IsNullOrWhiteSpace(entry.Key) && TryParse(entry.Value, out var gesture))
            {
                result[entry.Key] = gesture;
            }
        }

        return result;
    }
}
